name: build_and_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        toolchain: [llvm15]
        config: [clang-format, clang-tidy]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: bazelbuild/setup-bazelisk@v2

    - name: mount bazel cache
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: bazel-build-${{ matrix.toolchain }}-${{ matrix.config }}

    - run: |
        bazel \
          --bazelrc=.github/workflows/ci.bazelrc \
          build \
          --extra_toolchains=${{ matrix.toolchain }} \
          --config=${{ matrix.config}} \
          //...
  test:
    strategy:
      fail-fast: false
      matrix:
        toolchain: [gcc11, llvm15]
        feature: ['']
        include:
          - toolchain: llvm15
            feature: asan
          - toolchain: llvm15
            feature: tsan
          - toolchain: llvm15
            feature: ubsan

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: bazelbuild/setup-bazelisk@v2

    - name: mount bazel cache
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: bazel-test-${{ matrix.toolchain }}-${{ matrix.feature }}

    - run: |
        bazel \
          --bazelrc=.github/workflows/ci.bazelrc \
          test \
          --extra_toolchains=${{ matrix.toolchain }} \
          --features=${{ matrix.feature }} \
          //...
