name: build_and_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        bazel_command:
          - build --extra_toolchains=":llvm15" --config=clang-format
          - build --extra_toolchains=":llvm15" --config=clang-tidy

          - test --extra_toolchains=":llvm15"
          - test --extra_toolchains=":llvm15" --features=asan
          - test --extra_toolchains=":llvm15" --features=tsan
          - test --extra_toolchains=":gcc11"
          # TODO fix ubsan feature with llvm toolchain

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - uses: bazelbuild/setup-bazelisk@v2

    - name: mount bazel cache
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: bazel

    - run: |
        bazel \
          --bazelrc=.github/workflows/ci.bazelrc \
          ${{ matrix.bazel_command }} //...
